### ISSUE TITLE
little typo fix needed

### ISSUE THREAD

**Issue by mseyne** [open-source-society/ossu-ui#3]
Open Source Society Univesity client-side application

Unive**r**sity

**Comment by jdinartejesus** [comment]
Fixed, right @ericdouglas?  :+1:

**Comment by jdinartejesus** [comment]
Thanks @mseyne for having noticed. 

If you find something else or want to joins us. 
Feel free to help!

**Comment by SoullessWaffle** [comment]
Not fixed yet
![Not fixed yet](http://puu.sh/kFaay/98916a50d1.png)

**Comment by mseyne** [comment]
Not fixed yes :)

**Comment by ericdouglas** [comment]
@mseyne :+1: 

Fixed! :sweat_smile:

**Comment by jdinartejesus** [comment]
:+1:

**Comment by ericdouglas** [comment]
@mseyne sent an invitation to you :wink:

**Comment by mseyne** [comment]
Thank you @ericdouglas :)
